### ISSUE TITLE
Tilmeld som "jeg har corona" eller tilmeld som "jeg støtter"

### ISSUE THREAD

**Issue by daniel-davidsen** [covid19-group/c19#5]
Hey Gutter, mega fedt projekt.
Jeg har delt det på FB men sidder selv på jeres side og tænkte at tilmelde mig indtil jeg så "Vi sender dig dagligt et link med spørgsmål" og det ledte mig til at forstå det som tilmeld som om "jeg er smittet" måske en bedre formulering kan medfører færre fejl tilmeldinger.

To andre små bud.
- en kontakt side ville være rart 
- et overview over hvormange i har registeret ( men det antager jeg næsten kommer)

BTW har I brug for en hånd så hjælper jeg gerne✌️

I er for seje🤘

**Comment by holgerthorup** [comment]
Hi @daniel-davidsen,

Thank you for sharing the project – and we appreciate your suggestions.

We are purposefully not showing data as (a) we have yet to collect a significant amount of data to secure individual privacy before publishing anything and (b) we haven't started collecting medical information yet because of missing legal/political clearance.

I will make sure that we add a contact section. We recently added names of currently involved volunteers here: https://c19.dk/faq

**Comment by holgerthorup** [comment]
With respect to "Vi sender dig dagligt et link med spørgsmål", we're looking for _everyone_ to submit _every day_ to get the full picture. That includes people who _do not_ have symptoms (yet). 

We know this may seem like a big workload for some, so we're trying to limit the questionnaire to absolute minimum (w/ involvement of authorized doctors and professors) _and_ have simple option to just duplicate your must recent report – if nothing has changed.

**Comment by holgerthorup** [comment]
I've added contact information for the main drivers behind the project to the FAQ.
